
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRECHAVES ABREPAREN ALERTA DESLIGAR DIFERENTE DISPOSITIVO DOISPONTOS ELOGICO ENTAO ENVIAR FECHACHAVES FECHAPAREN ID IGUAL IGUALIGUAL LIGAR MAIOR MAIORIGUAL MENOR MENORIGUAL NUM PARA PONTO SE SENAO SET STRING TODOS VIRGULAprogram : devices cmdsdevices : device devicesdevices : devicedevice : DISPOSITIVO DOISPONTOS ABRECHAVES ID VIRGULA ID FECHACHAVESdevice : DISPOSITIVO DOISPONTOS ABRECHAVES ID FECHACHAVEScmds : cmd PONTO cmdscmds : cmd PONTOcmd : SET ID IGUAL varcmd : SE obs ENTAO actcmd : SE obs ENTAO act SENAO actcmd : actobs : ID op_logic varobs : ID op_logic var ELOGICO obsop_logic : MAIOR\n| MENOR\n| MAIORIGUAL\n| MENORIGUAL\n| IGUALIGUAL\n| DIFERENTEvar : NUM\n| IDact : LIGAR IDact : DESLIGAR IDact : ENVIAR ALERTA ABREPAREN STRING FECHAPAREN IDact : ENVIAR ALERTA ABREPAREN STRING VIRGULA ID FECHAPAREN IDact : ENVIAR ALERTA ABREPAREN STRING FECHAPAREN PARA TODOS DOISPONTOS lista_idslista_ids : ID VIRGULA lista_idslista_ids : ID'
    
_lr_action_items = {'DISPOSITIVO':([0,3,42,53,],[4,4,-5,-4,]),'$end':([1,5,15,23,],[0,-1,-7,-6,]),'SET':([2,3,13,15,42,53,],[7,-3,-2,7,-5,-4,]),'SE':([2,3,13,15,42,53,],[8,-3,-2,8,-5,-4,]),'LIGAR':([2,3,13,15,25,42,43,53,],[10,-3,-2,10,10,-5,10,-4,]),'DESLIGAR':([2,3,13,15,25,42,43,53,],[11,-3,-2,11,11,-5,11,-4,]),'ENVIAR':([2,3,13,15,25,42,43,53,],[12,-3,-2,12,12,-5,12,-4,]),'DOISPONTOS':([4,54,],[14,56,]),'PONTO':([6,9,19,20,35,36,37,38,48,50,57,58,59,61,],[15,-11,-22,-23,-21,-8,-20,-9,-10,-24,-25,-26,-28,-27,]),'ID':([7,8,10,11,22,24,26,27,28,29,30,31,32,41,44,45,46,55,56,60,],[16,18,19,20,34,35,35,-14,-15,-16,-17,-18,-19,47,18,50,52,57,59,59,]),'ALERTA':([12,],[21,]),'ABRECHAVES':([14,],[22,]),'IGUAL':([16,],[24,]),'ENTAO':([17,35,37,39,49,],[25,-21,-20,-12,-13,]),'MAIOR':([18,],[27,]),'MENOR':([18,],[28,]),'MAIORIGUAL':([18,],[29,]),'MENORIGUAL':([18,],[30,]),'IGUALIGUAL':([18,],[31,]),'DIFERENTE':([18,],[32,]),'SENAO':([19,20,38,50,57,58,59,61,],[-22,-23,43,-24,-25,-26,-28,-27,]),'ABREPAREN':([21,],[33,]),'NUM':([24,26,27,28,29,30,31,32,],[37,37,-14,-15,-16,-17,-18,-19,]),'STRING':([33,],[40,]),'VIRGULA':([34,40,59,],[41,46,60,]),'FECHACHAVES':([34,47,],[42,53,]),'ELOGICO':([35,37,39,],[-21,-20,44,]),'FECHAPAREN':([40,52,],[45,55,]),'PARA':([45,],[51,]),'TODOS':([51,],[54,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,13,]),'device':([0,3,],[3,3,]),'cmds':([2,15,],[5,23,]),'cmd':([2,15,],[6,6,]),'act':([2,15,25,43,],[9,9,38,48,]),'obs':([8,44,],[17,49,]),'op_logic':([18,],[26,]),'var':([24,26,],[36,39,]),'lista_ids':([56,60,],[58,61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','parser.py',13),
  ('devices -> device devices','devices',2,'p_devices_mult','parser.py',20),
  ('devices -> device','devices',1,'p_devices_one','parser.py',24),
  ('device -> DISPOSITIVO DOISPONTOS ABRECHAVES ID VIRGULA ID FECHACHAVES','device',7,'p_device_com_observacao','parser.py',28),
  ('device -> DISPOSITIVO DOISPONTOS ABRECHAVES ID FECHACHAVES','device',5,'p_device_sem_observacao','parser.py',33),
  ('cmds -> cmd PONTO cmds','cmds',3,'p_cmds','parser.py',37),
  ('cmds -> cmd PONTO','cmds',2,'p_cmds_last','parser.py',41),
  ('cmd -> SET ID IGUAL var','cmd',4,'p_cmd_set','parser.py',45),
  ('cmd -> SE obs ENTAO act','cmd',4,'p_cmd_if','parser.py',49),
  ('cmd -> SE obs ENTAO act SENAO act','cmd',6,'p_cmd_if_else','parser.py',53),
  ('cmd -> act','cmd',1,'p_cmd_acao','parser.py',57),
  ('obs -> ID op_logic var','obs',3,'p_obs_simples','parser.py',61),
  ('obs -> ID op_logic var ELOGICO obs','obs',5,'p_obs_composta','parser.py',65),
  ('op_logic -> MAIOR','op_logic',1,'p_op_logic','parser.py',69),
  ('op_logic -> MENOR','op_logic',1,'p_op_logic','parser.py',70),
  ('op_logic -> MAIORIGUAL','op_logic',1,'p_op_logic','parser.py',71),
  ('op_logic -> MENORIGUAL','op_logic',1,'p_op_logic','parser.py',72),
  ('op_logic -> IGUALIGUAL','op_logic',1,'p_op_logic','parser.py',73),
  ('op_logic -> DIFERENTE','op_logic',1,'p_op_logic','parser.py',74),
  ('var -> NUM','var',1,'p_var','parser.py',78),
  ('var -> ID','var',1,'p_var','parser.py',79),
  ('act -> LIGAR ID','act',2,'p_act_ligar','parser.py',83),
  ('act -> DESLIGAR ID','act',2,'p_act_desligar','parser.py',87),
  ('act -> ENVIAR ALERTA ABREPAREN STRING FECHAPAREN ID','act',6,'p_act_alerta_simples','parser.py',91),
  ('act -> ENVIAR ALERTA ABREPAREN STRING VIRGULA ID FECHAPAREN ID','act',8,'p_act_alerta_var','parser.py',95),
  ('act -> ENVIAR ALERTA ABREPAREN STRING FECHAPAREN PARA TODOS DOISPONTOS lista_ids','act',9,'p_act_broadcast','parser.py',99),
  ('lista_ids -> ID VIRGULA lista_ids','lista_ids',3,'p_lista_ids','parser.py',103),
  ('lista_ids -> ID','lista_ids',1,'p_lista_ids_single','parser.py',107),
]
